# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               VHL Developers
tagline:             'software engineering blog'
description:         'A blog written by the software engineering team at <a href="https://vistahigherlearning.com>Vista Higher Learning</a>"'
url:                 https://vistahigherlearning.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Dev Bot
  url:               https://vistahigherlearning.com
  email:             foo@example.com
